[project]
name = "nil-ws-api-graphql"
version = "0.1.0"
description = "API GraphQL de NIL"
authors = ["Antonio F. G. Sevilla <afgs@ucm.es>"]
requires-python = "~=3.7"
dependencies = [
    "ariadne~=0.9.0",
    "daphne~=2.4.0",
    "graphql-core~=3.0.2",
    "regex~=2020.1",
    "requests~=2.22",
]
