[tool.poetry]
name = "nil-ws-api-graphql"
version = "0.1.0"
description = "API GraphQL de NIL"
authors = ["Antonio F. G. Sevilla <afgs@ucm.es>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22"
daphne = "^2.4"
ariadne = "^0.9.0"
regex = "^2020.1"
