openapi: 3.0.1

info:
  title: Idilyco API
  description: |
    Este documento describe la _API_ del proyecto Idilyco, según el estándar OpenAPI 3.0.1
  version: 0.1.0

tags:
  - name: PT1
    description: |
      ## Simplificación de texto

      Responsable: Susana
  - name: PT2
    description: |
      ## Resúmenes

      Responsable: Alberto

  - name: grafeno
    description: Herramienta de grafos semánticos.
    externalDocs:
      description: Más información sobre la librería de generación de resúmenes.
      url: https://grafeno.readthedocs.io/en/latest/

servers:
  - url: http://mistela.fdi.ucm.es/idilyco-api/v1

paths:
  /resumen/{idioma}:
    $ref: 'grafeno.yaml#/Resumenes'

